all:
    hosts:
        local:
            ansible_host: localhost
            ansible_connection: local
    children:
        una:
            hosts:
                base:
                  ansible_host: 10.0.112.123
                rt:
                  ansible_host: rt.crhad.una
                dns:
                  ansible_host: dns.crhad.una
                ns1:
                  ansible_host: ns1.crhad.una
                ns2:
                  ansible_host: ns2.crhad.una
                mx1:
                  ansible_host: mx1.crhad.una
                mx2:
                  ansible_host: mx2.crhad.una

